feat: Merge models passed from context and props
mongodb-js/connect-backbone-to-react pull request #15
Opened 2017-10-11 22:14 UTC by spencer-brown

Fixes https://github.com/mongodb-js/connect-backbone-to-react/issues/14.

2017-10-13 03:07 UTC, hswolff requested changes
One small change then should be good to go.

2017-10-13 03:07 UTC, hswolff commented on test/backbone-provider.test.js
> +        .find('.name')
Curious if we should put `<ConnectedChild />` within a div with a className so we can scope this lookup to just the child to be more explicit about where the props value is coming from?

2017-11-27 00:16 UTC, hswolff commented
Bump on this, would love to get this merged.

2017-12-09 00:03 UTC, ghmeier commented
Hey @hswolff, just made the quick change adding a class to the wrapper div since @spencer-brown has been busy. Hyped to get this feature added.

2017-12-11 14:11 UTC, merged

2017-12-11 14:11 UTC, hswolff commented
Thanks @ghmeier !

2017-12-11 14:13 UTC, hswolff commented
Published as `v1.5.0`